name: Benchmarks

on:
  pull_request:
    paths:
      - .github/workflows/benchmarks.yml
      - scripts/benchmark.py
      - scripts/requirements-bm.txt
      - src/**

jobs:
  benchmarks:
    runs-on: ubuntu-24.04
    steps:
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install libunwind-dev binutils-dev libiberty-dev

      - name: Install Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          path: austin-base

      - name: Compile Austin from the base branch
        run: |
          cd austin-base
          autoreconf --install
          ./configure --enable-debug=symbols
          make
          cd -

      - uses: actions/checkout@v3
        with:
          path: austin

      - name: Compile Austin from the PR
        run: |
          cd austin
          autoreconf --install
          ./configure --enable-debug=symbols
          make
          cd -

      - name: Install runtime dependencies
        run: |
          python3.13 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          cd austin
          pip install -r scripts/requirements-bm.txt
          cd -

      - name: Run benchmarks
        shell: bash
        env:
          PYTHONPATH: "."
        run: |
          set -eo pipefail
          ulimit -c unlimited
          echo "core.%p" | sudo tee /proc/sys/kernel/core_pattern
          source .venv/bin/activate
          mv ${{ github.workspace}}/austin-base/src/austin ${{ github.workspace}}/austin/src/austin-base
          cd austin
          python scripts/benchmark.py --format markdown | tee ${{ github.workspace}}/comment.txt
          cd -

      - name: Post results on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: benchmarks
          path: ${{ github.workspace}}/comment.txt
